### ISSUE TITLE
Buid failed: could not find `windows` in `os`

### ISSUE THREAD

**Issue by rodrigocfd** [rust-lang/docs.rs#1339]
**Crate name:** winsafe
**Build failure link:** https://docs.rs/crate/winsafe/0.0.2/builds/369740

**Additional details:**
Do I need any special configuration for a Windows build?

```
[INFO] [stderr] 2 | use std::os::windows::ffi::OsStrExt;
[INFO] [stderr]   |              ^^^^^^^ could not find `windows` in `os`
```

**Comment by Nemo157** [comment]
You can configure your crate to only build the documentation for the windows targets [using crate metadata](https://docs.rs/about/metadata):

```toml
[package.metadata.docs.rs]
targets = [
  "x86_64-pc-windows-msvc",
  # ... other windows targets you care about
]
```
