### ISSUE TITLE
Browser's bottom-left URL display hides last entry in sidebar

### ISSUE THREAD

**Issue by michaeljones** [rust-lang/docs.rs#1761]
This has caught me out today a few times on some crates. I've looked but cannot see a similar issue reported at the moment.

Docs pages have lots of links on them. When a mouse is over a link, the browser (firefox in this case) shows the URL in the bottom left and that hides the last entry in the side bar even when the sidebar is scrolled to the bottom:

![image](https://user-images.githubusercontent.com/5390/178523613-ed552c1c-e90e-4f9f-be42-af56f7ff0f3b.png)

vs:

![image](https://user-images.githubusercontent.com/5390/178523791-c247a724-f2e2-48ce-9816-781b429a9bd2.png)

It is possible to keep scrolling so that the main page scrolls and the footer comes in to view and lifts everything enough to resolve the issue but I think it is possibly preferable to add ~20px of margin/padding at the bottom of the sidebar to stop this happening?

I assume this happens for everyone but I recognise there might be something off with my set up though I use firefox without any significant customisations.

**Comment by Nemo157** [comment]
There is meant to be some padding at the bottom (you can see on https://doc.rust-lang.org/nightly/std it has some), it looks like there's an issue with our CSS overrides leaking a SASS variable into the output

```css
#rustdoc_body_wrapper .sidebar {
  height: calc(100vh - $top-navbar-height);
}
```

If I manually fix that to

```css
#rustdoc_body_wrapper .sidebar {
  height: calc(100vh - 32px);
}
```

then the padding reappears.
