### ISSUE TITLE
vendored normalize.css does strange things to html details/summary tags

### ISSUE THREAD

**Issue by pacak** [rust-lang/docs.rs#1873]
Consider self hosted documentation, it is clear that usage examples are expandable
https://pacak.github.io/bpaf/bpaf/fn.short.html

The same function as hosted on docs.rs - it is NOT clear that they are expandable.
https://docs.rs/bpaf/0.6.1/bpaf/fn.short.html

tags in question

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/summary
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details

css in question is hosted here: https://docs.rs/-/static/vendored.css?0-6-0-b194f43-2022-09-25
```css
article,
aside,
details,
figcaption,
figure,
footer,
header,
hgroup,
main,
menu,
nav,
section,
summary /* <- this part */ {
 display:block
}
```
