### ISSUE TITLE
Can't build docs for my crate (⇒ add ability to set environment variables?)

### ISSUE THREAD

**Issue by pkgw** [rust-lang/docs.rs#191]
I just uploaded a new crate, [slurm-sys](https://crates.io/crates/slurm-sys), which provides bindings to a C library called `libslurm`. However, my docs won't currently build on docs.rs ([failure](https://docs.rs/crate/slurm-sys/0.1.0/builds/93695)) because on Debian Jessie, the dev packages for `libslurm` don't include a pkg-config file, which my `build.rs` expects to exist.

If I could set environment variables in the docs.rs build environment, I could set `SLURM_NO_PKG_CONFIG` and I think everything would work; and I think this would be the appropriate thing for users to do when no pkg-config file is present. But as far as I can tell, it isn't possible to set this environment variable for the docs.rs build.

Is that correct? Is there another workaround? It wouldn't be the most elegant, but if there were a way for my `build.rs` script to detect that it is running inside the docs.rs environment, I could add special-case code.

**Comment by nickbabcock** [comment]
I would also like environment variables to be configurable. In the meantime, I worked around it as follows:

In Cargo.toml

```toml
[package.metadata.docs.rs]
rustc-args = ["--cfg",  "<name>_docs_rs"]
rustdoc-args = ["--cfg", "<name>_docs_rs"]
```

In build script:

```rust
#[cfg(<name>_docs_rs)]
fn detect_version() -> String {
    String::from("5.5")
}

#[cfg(not(<name>_docs_rs))]
fn detect_version() -> String {
    // Use environment variables
}
```

**Comment by pkgw** [comment]
That's clever! But definitely kludgey :-)

**Comment by kornelski** [comment]
I wasn't aware of the metadata table!

```toml
[package.metadata.docs.rs]
features = [ "docs-rs" ]
```

That would work for me.
