### ISSUE TITLE
grouping targets in the target list

### ISSUE THREAD

**Issue by fbstj** [rust-lang/docs.rs#2171]
I came across #2170 and the screenshot inspired me to ask if it makes sense to group the targets by platform tier

> ![image](https://user-images.githubusercontent.com/3050060/256608423-fa263988-f618-4e4a-8ad2-b804e448825f.png)

**Comment by Nemo157** [comment]
AFAIK there's no tier metadata published with the targets, <https://github.com/rust-lang/rust/blob/master/src/doc/rustc/src/platform-support.md> is the only place I know we could get this info.

It might also be that rustc's tiers don't match the crate's tiers, a lot of the time the only reason crates build for more than a single target is that they don't override the default target list. If we're going to provide grouping it might be best set by the crate itself

```toml
[[package.metadata.docs.rs.target-groups]]
label = "Fully tested"
targets = [ ... ]
[[package.metadata.docs.rs.target-groups]]
label = "Build only"
targets = [ ... ]
```
