### ISSUE TITLE
Crate succeeds to build, but some modules are unreachable

### ISSUE THREAD

**Issue by kands-code** [rust-lang/docs.rs#2579]
### Crate name

rmatrix_ks

### Build failure link

https://docs.rs/crate/rmatrix_ks/0.3.7/builds/1313071

### Additional details

I used `cargo doc --all-features` to compile the document locally, and everything was displayed normally.

![image](https://github.com/user-attachments/assets/0245e9d8-e430-4eaf-9f84-32972cb06902)

However, when I uploaded it to docs.rs, I found that some module pages were not displayed, specifically the `serde` module.

![image](https://github.com/user-attachments/assets/0343050b-6a11-4bf2-9586-0980a3d90f1b)

I don't know why. My configuration is as follows:

```toml
[package.metadata.doc.rs]
features = ["rand_mat", "rayon_mat", "serde_mat"]
all-features = true
no-default-features = true
```

> serde module has config `#![cfg(serde_mat)]`

I initially thought it was caused by `doc_cfg`, but when I removed `doc_cfg` and tried to solve this, nothing changed.
