### ISSUE TITLE
I don't know why building error occur

### ISSUE THREAD

**Issue by kaaatsu32329** [rust-lang/docs.rs#2691]
### Crate name

echo-state-network

### Build failure link

https://docs.rs/crate/echo-state-network/0.0.1/builds

### Additional details

```
# pre-build errors
invalid Cargo.toml syntax

Stack backtrace:
0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
1: rustwide::prepare::Prepare::prepare
2: rustwide::build::BuildDirectory::run
3: docs_rs::docbuilder::rustwide_builder::RustwideBuilder::build_package
4: prometheus::histogram::Histogram::observe_closure_duration
5: docs_rs::build_queue::BuildQueue::build_next_queue_package
6: docs_rs::utils::queue_builder::queue_builder
7: cratesfyi::CommandLine::handle_args
8: cratesfyi::main
9: std::sys::backtrace::__rust_begin_short_backtrace
10: std::rt::lang_start::{{closure}}
11: std::rt::lang_start_internal
12: main
13: __libc_start_main
at /build/glibc-uZu3wS/glibc-2.27/csu/../csu/libc-start.c:310
14: _start
```

It seems to be no element of error in Cargo.toml.

```toml
[package]
name = "echo-state-network"
version = "0.0.1"
edition = "2024"
license = "MIT"
description = "A Rust library for Echo State Networks"
repository = "https://github.com/kaaatsu32329/esn-rs"

[features]
default = ["plot"]
plot = ["plotters"]

[dependencies]
assert_approx_eq = "1"
chrono = "0.4"
env_logger = "0.11"
log = "0.4"
nalgebra = { version = "0.33", features = ["serde-serialize"] }
petgraph = "0.6"
petgraph-gen = "0.1"
plotters = { version = "0.3", optional = true }
rand = "0.8"
rand_distr = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
```
