### ISSUE TITLE
Build failure on last nightly despite `rust-toolchain.toml`

### ISSUE THREAD

**Issue by hirrolot** [rust-lang/docs.rs#2780]
### Crate name

teloxide

### Build failure link

https://docs.rs/crate/teloxide/0.14.0/builds/1924379

### Additional details

Our [`rust-toolchain.toml`] is:

[`rust-toolchain.toml`]: https://github.com/teloxide/teloxide/blob/9d66046bebf30835251721e8a878f5e4d814aa60/rust-toolchain.toml

```toml
[toolchain]
channel = "nightly-2025-02-02"
components = ["rustfmt", "clippy"]
profile = "minimal"
```

however, docs.rs selects `2025-03-28` nightly instead of our `2025-02-02`, which triggers the errors. Building documentation on our nightly works just fine.
