### ISSUE TITLE
uuid 0.7.3 not building

### ISSUE THREAD

**Issue by kinggoesgaming** [rust-lang/docs.rs#321]
it indicates that winapi isnt available. however we ensure that we dont have winapi linked on *nix platform. According to the Cargo.toml:

```toml
[target."cfg(windows)".dependencies.winapi]
version = "0.3"
optional = true
```

https://docs.rs/crate/uuid/0.7.3/builds/150373
