### ISSUE TITLE
rustdoc-args is ignored

### ISSUE THREAD

**Issue by Recmo** [rust-lang/docs.rs#423]
The `zkp-stark` crate contains the following in its `Cargo.toml`:

```toml
[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", ".cargo/katex-header.html"]
```

The file `.cargo/katex-header.html` is included in the package (as can be seen [here](https://docs.rs/crate/zkp-stark/0.1.1/source/)).

Yet the generated docs do not include this header, and become unreadable: https://docs.rs/zkp-stark/0.1.1/zkp_stark/fn.prove.html
