### ISSUE TITLE
Add  support for more targets

### ISSUE THREAD

**Issue by rubberduck203** [rust-lang/docs.rs#563]
**Crate name:** stm32f3-discovery
**Build failure link:** https://docs.rs/crate/stm32f3-discovery/0.1.2/builds/212158

**Additional details:**

Crates targeting ARM Cortex-M processors fail to build because docs.rs currently doesn't support the `thumbv*` targets.

This can be worked around by setting the default target to `x86_64-unknown-linux-gnu` per https://github.com/stm32-rs/stm32f3xx-hal/issues/46.

```toml
[package.metadata.docs.rs]
default-target = "x86_64-unknown-linux-gnu"
```

Possibly related to https://github.com/rust-lang/docs.rs/issues/343#issuecomment-525888748
