### ISSUE TITLE
Remove environment variables from docker-compose.yml

### ISSUE THREAD

**Issue by jyn514** [rust-lang/docs.rs#745]
Currently we have both `environment` and `env_file`. Since we have reasonable defaults in `.env.sample `, there's no need to have the explicit variables and they seem to be overriding the env file:

```
         environment:
            CRATESFYI_RUSTWIDE_WORKSPACE: /opt/docsrs/rustwide
            CRATESFYI_DATABASE_URL: postgresql://cratesfyi:password@db
            S3_ENDPOINT: http://s3:9000
            AWS_ACCESS_KEY_ID: cratesfyi
            AWS_SECRET_ACCESS_KEY: secret_key
        env_file:
            - .env
```
